MENU_CATEGORIES = [
    {
        'slug': 'starters',
        'title': 'Закуски',
        'icon': 'bi-egg-fried',
        'items': [
            {
                'name': 'Тартар из говядины',
                'description': 'Мраморная говядина, каперсы, яичный желток, трюфельное масло',
                'price': 890,
                'weight': '180 г',
                'image': 'https://images.unsplash.com/photo-1544025162-d76694265947?w=200&h=200&fit=crop',
            },
            {
                'name': 'Устрицы Fine de Claire',
                'description': 'С лимоном, соусом mignonette и хреном',
                'price': 450,
                'weight': '1 шт.',
                'image': 'https://images.unsplash.com/photo-1559339352-11d035aa65de?w=200&h=200&fit=crop',
            },
            {
                'name': 'Ассорти сыров',
                'description': 'Камамбер, горгонзола, пармезан, мед, орехи',
                'price': 1250,
                'weight': '250 г',
                'image': 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=200&h=200&fit=crop',
            },
            {
                'name': 'Брускетта с томатами',
                'description': 'Хлеб чиабатта, базилик, оливковое масло',
                'price': 420,
                'weight': '160 г',
                'image': 'https://images.unsplash.com/photo-1603048297172-c92544798d5a?w=200&h=200&fit=crop',
            },
        ],
    },
    {
        'slug': 'soups',
        'title': 'Супы',
        'icon': 'bi-cup-hot',
        'items': [
            {
                'name': 'Бульон с домашней лапшой',
                'description': 'Куриный бульон, лапша, зелень, яйцо пашот',
                'price': 480,
                'weight': '350 мл',
                'image': 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=200&h=200&fit=crop',
            },
            {
                'name': 'Крем-суп из тыквы',
                'description': 'Тыква, сливки, тыквенные семечки, крем-фреш',
                'price': 520,
                'weight': '300 мл',
                'image': 'https://images.unsplash.com/photo-1476718406336-bb5a9690ee2a?w=200&h=200&fit=crop',
            },
            {
                'name': 'Уха из красной рыбы',
                'description': 'Лосось, форель, картофель, укроп, лимон',
                'price': 690,
                'weight': '350 мл',
                'image': 'https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=200&h=200&fit=crop',
            },
        ],
    },
    {
        'slug': 'main',
        'title': 'Горячие блюда',
        'icon': 'bi-fire',
        'items': [
            {
                'name': 'Стейк рибай',
                'description': 'Мраморная говядина, овощи гриль, соус перечный',
                'price': 2890,
                'weight': '300 г',
                'image': 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=200&h=200&fit=crop',
            },
            {
                'name': 'Филе лосося на гриле',
                'description': 'Лосось, спаржа, лимонный соус, микрозелень',
                'price': 1650,
                'weight': '220 г',
                'image': 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=200&h=200&fit=crop',
            },
            {
                'name': 'Утка по-пекински',
                'description': 'Запечённая утка, блинчики, соус хойсин, огурцы',
                'price': 1980,
                'weight': '350 г',
                'image': 'https://images.unsplash.com/photo-1585032226651-759b368d7246?w=200&h=200&fit=crop',
            },
            {
                'name': 'Ризотто с белыми грибами',
                'description': 'Рис арборio, белые грибы, пармезан, трюфельное масло',
                'price': 980,
                'weight': '280 г',
                'image': 'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=200&h=200&fit=crop',
            },
            {
                'name': 'Баранья нога confit',
                'description': 'Томлёная баранина, пюре из сельдерея, соус из красного вина',
                'price': 2150,
                'weight': '320 г',
                'image': 'https://images.unsplash.com/photo-1518611012118-696072aa579a?w=200&h=200&fit=crop',
            },
        ],
    },
    {
        'slug': 'salads',
        'title': 'Салаты',
        'icon': 'bi-flower1',
        'items': [
            {
                'name': 'Цезарь с креветками',
                'description': 'Салат рomaine, креветки тигровые, пармезан, соус цезарь',
                'price': 850,
                'weight': '250 г',
                'image': 'https://images.unsplash.com/photo-1546793665-c74683f339c1?w=200&h=200&fit=crop',
            },
            {
                'name': 'Салат с уткой и апельсином',
                'description': 'Утиная грудка, микс салатов, апельсин, орехи пекan',
                'price': 920,
                'weight': '220 г',
                'image': 'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=200&h=200&fit=crop',
            },
            {
                'name': 'Греческий салат',
                'description': 'Фета, томаты, огурцы, оливки, красный лук',
                'price': 580,
                'weight': '280 г',
                'image': 'https://images.unsplash.com/photo-1540189549336-e6e99c3679fe?w=200&h=200&fit=crop',
            },
        ],
    },
    {
        'slug': 'drinks',
        'title': 'Напитки',
        'icon': 'bi-cup-straw',
        'items': [
            {
                'name': 'Домашний лимонад',
                'description': 'Мята, лимон, имбирь',
                'price': 350,
                'weight': '400 мл',
                'image': 'https://images.unsplash.com/photo-1621263764928-df1444c5e859?w=200&h=200&fit=crop',
            },
            {
                'name': 'Свежевыжатый сок',
                'description': 'Апельсин / яблоко / морковь',
                'price': 380,
                'weight': '300 мл',
                'image': 'https://images.unsplash.com/photo-1622597467836-f3285f2131b8?w=200&h=200&fit=crop',
            },
            {
                'name': 'Эспрессо / Америкano',
                'description': 'Кофе specialty',
                'price': 250,
                'weight': '150 мл',
                'image': 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=200&h=200&fit=crop',
            },
            {
                'name': 'Чай премиум',
                'description': 'Ассam / зелёный / травяной',
                'price': 320,
                'weight': '500 мл',
                'image': 'https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=200&h=200&fit=crop',
            },
        ],
    },
]

DESSERTS_SECTION = {
    'title': 'Торты и десерты',
    'subtitle': 'Мы с удовольствием поможем украсить ваше торжество или значимое событие',
    'items': [
        {
            'name': 'Наполеон',
            'description': 'Классический слоёный торт с заварным кремом',
            'price': 480,
            'weight': '150 г',
            'image': 'https://images.unsplash.com/photo-1578985545062-69928b1d9587?w=200&h=200&fit=crop',
        },
        {
            'name': 'Медовик',
            'description': 'Домашний медовый торт со сметанным кремом',
            'price': 450,
            'weight': '150 г',
            'image': 'https://images.unsplash.com/photo-1565958011703-44f9829ba187?w=200&h=200&fit=crop',
        },
        {
            'name': 'Тирамису',
            'description': 'Маскарпоне, печенье савоярди, ликёр, какao',
            'price': 520,
            'weight': '140 г',
            'image': 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=200&h=200&fit=crop',
        },
        {
            'name': 'Крем-брюле',
            'description': 'Ванильный крем с карамельной корочкой',
            'price': 420,
            'weight': '120 г',
            'image': 'https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?w=200&h=200&fit=crop',
        },
        {
            'name': 'Шоколадный фondant',
            'description': 'Тёплый шоколадный кекс с жидкой начинкой, мороженое',
            'price': 490,
            'weight': '130 г',
            'image': 'https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=200&h=200&fit=crop',
        },
        {
            'name': 'Торт на заказ',
            'description': 'Индивидуальный дизайн для банкетов и праздников — уточняйте у администратора',
            'price': None,
            'weight': 'от 2 кг',
            'image': 'https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=200&h=200&fit=crop',
        },
    ],
}
